server:
  port: 8081 # portの指定


spring:
  datasource:
    url: jdbc:mysql://localhost/p2112591?characterEncoding=UTF-8&serverTimezone=JST&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # デフォルト
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
  #    jndi-name: java:hoge/fuga # jndi
  jpa:
    show-sql: true