server:
  port: 8080 # portの指定

spring:
  datasource:
    url: jdbc:mysql://localhost/spring?characterEncoding=UTF-8&serverTimezone=JST&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # デフォルト
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
  #    jndi-name: java:hoge/fuga # JNDIを使用する場合
  jpa:
    show-sql: true
  flyway:
    enabled: false #